shared_variables:
  rightholder: Flinesoft
  project_name: HandySwift

rules:
  - xcode_build_phases:
      project_path: <:project_name:>.xcodeproj
      target_name: Framework
      run_scripts:
        SwiftLint: |
          if which swiftlint > /dev/null; then
              swiftlint
          else
              echo "warning: SwiftLint not installed, download it from https://github.com/realm/SwiftLint"
          fi

        ProjLint: |
          if which projlint > /dev/null; then
              projlint lint --xcode --timeout 2 --ignore-network-errors
          else
              echo "warning: ProjLint not installed, download it from https://github.com/JamitLabs/ProjLint"
          fi

  - xcode_project_navigator:
      project_path: <:project_name:>.xcodeproj
      sorted:
        - Framework
            - Sources
            - SupportingFiles
        - Tests
            - Sources
            - SupportingFiles
      inner_group_order:
        - assets
        - entitlements
        - plists
        - strings
        - others
        - [code_files, interfaces]
        - folders
      structure:
        - Framework:
            - Sources
            - SupportingFiles:
                - Info.plist
        - Tests:
            - Sources
            - SupportingFiles:
                - Info.plist
        - RootFiles:
            - beak.swift
            - .projlint.yml
            - .swiftlint.yml
            - Package.swift
        - Products
  - file_content_template:
      matching:
        .swiftlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/Framework/SwiftLint.stencil"
          parameters:
            rightholder: <:rightholder:>
        .projlint.yml:
          template_url: "https://raw.githubusercontent.com/JamitLabs/ProjLintTemplates/master/Framework/ProjLint.stencil"
          parameters:
            rightholder: <:rightholder:>
            project_name: <:project_name:>
  - file_existence:
      existing_paths:
        - .gitignore
        - .swiftlint.yml
        - README.md
        - LICENSE.md
        - beak.swift
        - <:project_name:>.xcodeproj/xcshareddata/IDETemplateMacros.plist
        - Framework/SupportingFiles/Info.plist
        - Tests/SupportingFiles/Info.plist
        - UITests/SupportingFiles/Info.plist
