# rule identifiers to exclude from running
disabled_rules:
- trailing_newline
- trailing_whitespace
- todo  # this is better solved via a build script

# some rules are only opt-in
opt_in_rules:
- empty_count
- missing_docs

# paths to include during linting. `--path` is ignored if present.
included:
- Sources

# paths to ignore during linting. Takes precedence over `included`.
excluded:
- Carthage

# configurable rules can be customized from this configuration file
line_length: 128