# Basic Configuration
opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_filter_count
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- convenience_type
- empty_collection_literal
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- explicit_type_interface
- fallthrough
- fatal_error_message
- file_name
- file_name_no_space
- file_types_order
- first_where
- flatmap_over_map_reduce
- function_default_parameter_at_end
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- indentation_width
- joined_default_parameter
- last_where
- legacy_multiple
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- missing_docs
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- nslocalizedstring_key
- number_separator
- object_literal
- operator_usage_whitespace
- optional_enum_case_matching
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefer_self_type_over_type_of_self
- private_action
- private_outlet
- prohibited_super_call
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
- type_contents_order
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- unused_declaration
- unused_import
- vertical_parameter_alignment_on_call
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- yoda_condition

included:
- Sources
- Tests

excluded:
- Tests/LinuxMain.swift

disabled_rules:
  - todo

# Rule Configurations
conditional_returns_on_newline:
  if_only: true

explicit_type_interface:
  allow_redundancy: true
  excluded:
    - local

file_name:
  suffix_pattern: "Ext"

identifier_name:
  max_length: 60
  excluded:
    - id
    - db
    - to

indentation_width:
  indentation_width: 2

line_length: 160

nesting:
  type_level: 3

trailing_comma:
  mandatory_comma: true

trailing_whitespace:
  ignores_comments: false

# Custom Rules
custom_rules:
  class_name_suffix_collection_view_controller:
    included: ".*.swift"
    regex: 'class +\w+(?<!CollectionViewController) *(?:<[^>]+>)? *: +\w+CollectionViewController'
    name: "Class Name Suffix View Controller"
    message: "All `CollectionViewController` subclasses should end on `CollectionViewController`."
    severity: warning
  class_name_suffix_table_view_controller:
    included: ".*.swift"
    regex: 'class +\w+(?<!TableViewController) *(?:<[^>]+>)? *: +\w+TableViewController'
    name: "Class Name Suffix View Controller"
    message: "All `TableViewController` subclasses should end on `TableViewController`."
    severity: warning
  class_name_suffix_view_controller:
    included: ".*.swift"
    regex: 'class +\w+(?<!ViewController) *(?:<[^>]+>)? *: +\w+ViewController'
    name: "Class Name Suffix View Controller"
    message: "All `ViewController` subclasses should end on `ViewController`."
    severity: warning
  closure_params_parantheses:
    included: ".*.swift"
    regex: '\{\s*\((?!self)[^):]+\)\s*in'
    name: "Unnecessary Closure Params Parantheses"
    message: "Don't use parantheses around non-typed parameters in a closure."
    severity: warning
  comment_type_note:
    included: ".*.swift"
    regex: '// *(?:WORKAROUND|HACK|WARNING)[:\\s]'
    name: "Comment Type NOTE"
    message: "Use a '// NOTE:' comment instead."
    severity: warning
  comment_type_refactor:
    included: ".*.swift"
    regex: '// *(?:TODO|NOTE)[:\\s][^\n]*(?:refactor|REFACTOR|Refactor)'
    name: "Comment Type REFACTOR"
    message: "Use a '// REFACTOR:' comment instead."
    severity: warning
  comment_type_todo:
    included: ".*.swift"
    regex: '// *(?:BUG|MOCK|FIXME|RELEASE|TEST)[:\\s]'
    name: "Comment Type TODO"
    message: "Use a '// TODO:' comment instead."
    severity: warning
  controller_class_name_suffix:
    included: ".*.swift"
    regex: 'class +\w+(?<!Navigation|View|Flow|Model)Controller'
    name: "Controller Class Name Suffix"
    message: "Only use the `Controller` class name suffix for Navigation-, View-, Model- or FlowControllers."
    severity: warning
  debug_log_level:
    included: ".*.swift"
    regex: 'log.debug\('
    name: "Debug Log Level"
    message: "Make sure to remove all debug log levels before committing."
    severity: warning
  empty_init_body:
    included: ".*.swift"
    regex: 'init\([^\{\n]*\) \{\s+\}'
    name: "Empty Init Body"
    message: "Don't use whitespace or newlines for the body of empty initializers – use `init() {}` instead."
    severity: warning
  empty_method:
    included: ".*.swift"
    regex: 'func [^\s\(]+\([^\{\n]*\) \{\s*\}'
    name: "Empty Method"
    message: "Don't keep empty methods in code without commenting inside why they are needed or a `// TODO: not yet implemented`."
    severity: warning
  empty_todo:
    included: ".*.swift"
    regex: '\/\/ TODO: (\[[\d-]+\])? *\n'
    name: "Empty Todo"
    message: "`// TODO:` comments should not be empty."
    severity: warning
  empty_type:
    included: ".*.swift"
    regex: '(?:class|protocol|struct|enum) [^\{]+\{\s*\}'
    name: "Empty Type"
    message: "Don't keep empty types in code without commenting inside why they are needed or a `// TODO: not yet implemented`."
    severity: warning
  flow_controller_variable_naming:
    included: ".*.swift"
    regex: '(?:let|var) +\w*(?:fc|FC|Fc|flowC|flowController|FlowController) *='
    name: "Flow Controller Variable Naming"
    message: "Always name your flow controller variables with the suffix `FlowCtrl`."
    severity: warning
  handyswift_delay:
    included: ".*.swift"
    regex: 'DispatchQueue\.\S+\.asyncAfter\(deadline:'
    name: "HandySwift Delay"
    message: "Use the `delay(by:qosClass:)` method of HandySwift instead of DispatchQueue for delayed code."
    severity: warning
  handyswift_delay_time_interval:
    included: ".*.swift"
    regex: 'delay\(by: ?\d'
    name: "HandySwift Delay TimeInterval"
    message: "Use one of the HandySwift TimeInterval extension methods like `.milliseconds(100)` instead."
    severity: warning
  handyswift_time_interval:
    included: ".*.swift"
    regex: ':\s*(?:Dispatch)?TimeInterval\s*=\s*(?:[1-9]|0\.0*[1-9])'
    name: "HandySwift TimeInterval"
    message: "Use one of the HandySwift (Dispatch)TimeInterval extension methods like `.milliseconds(100)` instead."
    severity: warning
  if_as_guard:
    included: ".*.swift"
    regex: '(?<=\n) *if [^\{]+\{\s*return\s*(?:nil){0,1}([^a-zA-z\n]*)\n*\s*\}(?! *else)'
    name: "If as Guard"
    message: "Don't use an if statement to just return – use guard for such cases instead."
    severity: warning
  late_force_unwrapping:
    included: ".*.swift"
    regex: '\(\S+\?\.\S+\)!'
    name: "Late Force Unwrapping"
    message: "Don't use ? first to force unwrap later – directly unwrap within the parantheses."
    severity: warning
  local_l10n:
    included: ".*.swift"
    regex: 'func \S+\s*\{\s*[^\}]*let l10n'
    name: "Local l10n"
    message: "Don't name local variable `l10n` – use a property instead and further specify with `localL10n` if needed."
    severity: warning
  log_prefix:
    included: ".*.swift"
    regex: 'log\.(?:verbose|debug|info|warning|error)\("(?:verbose|debug|info|warning|error).*"\)'
    name: "Logging Prefix"
    message: "Don't use logging prefixes with log.verbose/debug/info/warning/error – done automatically."
    severity: warning
  multiline_guard_end:
    included: ".*.swift"
    regex: 'guard\s*([^\n]*,\n)+([^\n]*\S *)else\s*\{'
    name: "Multiline Guard End"
    message: "Always close a multiline guard via `else {` on a new line indented like the opening `guard`."
    severity: warning
  multiline_guard_start:
    included: ".*.swift"
    regex: 'guard([^\n]*,\n)+[^\n]*else\s*\{'
    name: "Multiline Guard Start"
    message: "Always start a multiline guard via `guard` then a line break and all expressions indented."
    severity: warning
  multiple_closure_params:
    included: ".*.swift"
    regex: '\n *(?:[^\.\n=]+\.)+[^\(\s]+\([^\{\n]+\{[^\}\n]+\}\)\s*\{'
    name: "Multiple Closure Params"
    message: "Don't use multiple in-line closures – save one or more of them to variables instead."
    severity: warning
  none_case_enum:
    included: ".*.swift"
    regex: 'enum\s+[^\{]+\{(?:\s*\/\/[^\n]*)*(?:\s*case\s+[^\n]+)*\s*case\s+none[^\S]'
    name: "Non Case Enum"
    message: "Do not call enum cases `none` as you might run into problems with Optionals of this type."
    severity: warning
  remove_where_for_negative_filtering:
    included: ".*.swift"
    regex: '\.filter *\{ *!\$0\.[^\}&|]+\}'
    name: "Remove Where for Negative Filtering"
    message: "Use `remove(where:)` instead of `filter(where not ...)` for performance."
    severity: warning
  single_line_guard:
    included: ".*.swift"
    regex: 'guard[^\{]{2,80}else\s*\{\s*\n\s*return.{2,40}\}'
    name: "Single Line Guard"
    message: "Use a single line guard for simple checks."
    severity: warning
  singleton_default_private_init:
    included: ".*.swift"
    regex: 'class +(?<TYPE>\w+)(?:<[^\>]+>)? *\{.*static let `default`(?:: *\k<TYPE>)? *= *\k<TYPE>\(.*(?<=private) init\('
    name: "Singleton Default Private Init"
    message: "Singletons with a `default` object (pseudo-singletons) should not declare init methods as private."
    severity: warning
  singleton_shared_final:
    included: ".*.swift"
    regex: '(?<!final )class +(?<TYPE>\w+)(?:<[^\>]+>)? *\{.*static let shared(?:: *\k<TYPE>)? *= *\k<TYPE>\('
    name: "Singleton Shared Final"
    message: "Singletons with a single object (`shared`) should be marked as final."
    severity: warning
  singleton_shared_private_init:
    included: ".*.swift"
    regex: 'class +(?<TYPE>\w+)(?:<[^\>]+>)? *\{.*static let shared(?:: *\k<TYPE>)? *= *\k<TYPE>\(.*(?<= |\t|public|internal) init\('
    name: "Singleton Shared Private Init"
    message: "Singletons with a single object (`shared`) should declare their init method(s) as private."
    severity: warning
  singleton_shared_single_object:
    included: ".*.swift"
    regex: 'class +(?<TYPE>\w+)(?:<[^\>]+>)? *\{.*(?:static let shared(?:: *\k<TYPE>)? *= *\k<TYPE>\(.*static let \w+(?:: *\k<TYPE>)? *= *\k<TYPE>\(|static let \w+(?:: *\k<TYPE>)? *= *\k<TYPE>\(.*static let shared(?:: *\k<TYPE>)? *= *\k<TYPE>\()'
    name: "Singleton Shared Single Object"
    message: "Singletons with a `shared` object (real Singletons) should not have other static let properties. Use `default` instead (if needed)."
    severity: warning
  switch_associated_value_style:
    included: ".*.swift"
    regex: 'case\s+[^\(][^\n]*(?:\(let |[^\)], let)'
    name: "Switch Associated Value Style"
    message: "Always put the `let` in front of case – even if only one associated value captured."
    severity: warning
  todo_format:
    included: ".*.swift"
    regex: '\/\/ TODO: [^\n]{0,14}\n|\/\/ TODO: \[\S{1,12}\]|\/\/ TODO: [^\[]|\/\/ TODO: \[.{13}[^\]]|\/\/ TODO: \[[^a-z]{2}|\/\/ TODO: \[.{2}[^_]|\/\/ TODO: \[.{7}[^-]|\/\/ TODO: \[.{10}[^-]'
    name: "Todo Date"
    message: "All TODOs should have a format with creator credentials & date of their creation documented like this: `// TODO: [cg_YYYY-MM-DD] `."
    severity: warning
  todo_uppercase:
    included: ".*.swift"
    regex: '\/\/ ?tODO|\/\/ ?ToDO|\/\/ ?TOdO|\/\/ ?TODo|\/\/ ?todo|\/\/ ?Todo|\/\/ ?ToDo|\/\/ ?toDo'
    name: "Todo Uppercase"
    message: "All TODOs should be all-uppercased like this: `// TODO: [cg_YYYY-MM-DD] `."
    severity: warning
  todo_whitespacing:
    included: ".*.swift"
    regex: '\/\/TODO|\/\/ TODO\s|\/\/ TODO:[^ ]|\/\/ TODO:  |\/\/ TODO: \[[^\s]{0,10}\][^ ]'
    name: "Todo Whitespace"
    message: "All TODOs should exactly start like this (mind the whitespacing): `// TODO: [cg_YYYY-MM-DD] `."
    severity: warning
  tuple_index:
    included: ".*.swift"
    regex: '(\$\d|\w*[^\d \(\[\{])\.\d'
    name: "Tuple Index"
    message: "Prevent unwraping tuples by their index – define a typealias with named components instead."
    severity: warning
  unnecessary_case_break:
    included: ".*.swift"
    regex: '(case |default)(?:[^\n\}]+\n){2,}\s*break *\n|\n *\n *break(?:\n *\n|\n *\})'
    name: "Unnecessary Case Break"
    message: "Don't use break in switch cases – Swift breaks by default."
    severity: warning
  unnecessary_nil_assignment:
    included: ".*.swift"
    regex: 'var \S+\s*:\s*[^\s]+\?\s*=\s*nil'
    name: "Unnecessary Nil Assignment"
    message: "Don't assign nil as a value when defining an optional type – it's nil by default."
    severity: warning
  vertical_whitespaces_around_mark:
    included: ".*.swift"
    regex: '\/\/\s*MARK:[^\n]*(\n\n)|(\n\n\n)[ \t]*\/\/\s*MARK:|[^\s{]\n[^\n\/]*\/\/\s*MARK:'
    name: "Vertical Whitespaces Around MARK:"
    message: "Include a single vertical whitespace (empty line) before and none after MARK: comments."
    severity: warning
  view_controller_variable_naming:
    included: ".*.swift"
    regex: '(?:let|var) +\w*(?:vc|VC|Vc|viewC|viewController|ViewController) *='
    name: "View Controller Variable Naming"
    message: "Always name your view controller variables with the suffix `ViewCtrl`."
    severity: warning
  whitespace_around_range_operators:
    included: ".*.swift"
    regex: '\w\.\.[<\.]\w'
    name: "Whitespace around Range Operators"
    message: "A range operator should be surrounded by a single whitespace."
    severity: warning
  whitespace_comment_start:
    included: ".*.swift"
    regex: '[^:#\]\}\)][^:#\]\}\)]\/\/[^\s\/]'
    name: "Whitespace Comment Start"
    message: "A comment should always start with a whitespace."
    severity: warning
